"use client";

import dynamic from "next/dynamic";
import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Braces, Check, ChevronRight, CircleDot, Github, Globe2, Instagram, Layers3, Mail, Menu, MessageCircle, PanelTop, Rocket, Search, ServerCog, ShieldCheck, Workflow, X, Zap } from "lucide-react";
import { useState } from "react";

const HeroScene = dynamic(() => import("./HeroScene"), { ssr: false, loading: () => <div className="scene-loading" aria-hidden="true" /> });
const navItems = [["Hakkımda", "#hakkimda"], ["Projeler", "#projeler"], ["Hizmetler", "#hizmetler"], ["Süreç", "#surec"], ["İletişim", "#iletisim"]];
const skills = ["React", "TypeScript", "Node.js", "Tailwind CSS", "API Integration", "Admin Panels", "SEO", "Performance", "GitHub", "Deployment"];
const services = [
  { icon: Globe2, title: "Web Sitesi Geliştirme", text: "Markanı doğru anlatan, mobil öncelikli ve hızlı web deneyimleri." },
  { icon: PanelTop, title: "Kurumsal Tanıtım Siteleri", text: "Güven oluşturan, ziyaretçiyi net aksiyonlara yönlendiren yapılar." },
  { icon: Layers3, title: "Ürün / Katalog Siteleri", text: "Ürünleri kolay keşfedilir ve yönetilebilir biçimde sunan arayüzler." },
  { icon: ServerCog, title: "Admin Panel ve İçerik Yönetimi", text: "Teknik bilgi gerektirmeden güncellenebilen pratik yönetim araçları." },
  { icon: Workflow, title: "API Entegrasyonları", text: "Farklı sistemleri bir araya getiren güvenli ve sürdürülebilir bağlantılar." },
  { icon: Rocket, title: "Performans, SEO ve Yayına Alma", text: "Ölçülebilir hız, teknik SEO ve sorunsuz yayın süreçleri." },
];
const process = ["İhtiyacı Anlama", "Tasarım ve Yapı Planı", "Geliştirme", "Test ve Mobil Kontrol", "Yayına Alma", "Bakım ve Geliştirme"];
const reveal = { initial: { opacity: 0, y: 28 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-80px" }, transition: { duration: 0.65 } };

function SectionLabel({ index, children }: { index: string; children: React.ReactNode }) { return <div className="section-label"><span>{index}</span><span>{children}</span></div>; }

function SteamMockup() { return <div className="project-visual steam-visual"><div className="mock-window"><div className="window-bar"><span /><span /><span /><b>eHub.console</b></div><div className="steam-layout"><div className="steam-sidebar"><strong>LIBRARY</strong><i className="active" /><i /><i /><i /></div><div className="steam-main"><div className="flow-row"><span>App ID</span><b>480</b><ChevronRight size={14} /><em>QUEUE</em></div><div className="game-cards"><article>01<span>READY</span></article><article>02<span>SYNC</span></article><article>03<span>ADD</span></article></div><div className="terminal-line"><span>$</span> automation.run()<i /></div></div></div></div><div className="metric-chip"><Zap size={13} /> AUTO FLOW</div></div>; }
function CoachMockup() { return <div className="project-visual coach-visual"><div className="coach-orbit" /><div className="phone-card"><div className="phone-top"><span>ÇÇE</span><Menu size={14} /></div><div className="athlete-silhouette"><span>GÜCÜNÜ<br />KEŞFET.</span></div><div className="phone-stats"><b>12W<small>Program</small></b><b>24/7<small>Takip</small></b></div></div><div className="schedule-card"><span>BUGÜN</span><b>18:30</b><small>Fonksiyonel Antrenman</small><i /></div></div>; }
function IndustryMockup() { return <div className="project-visual industry-visual"><div className="catalog-window"><div className="catalog-nav"><strong>AZ.</strong><span>PARÇALAR</span><Search size={13} /></div><div className="part-grid"><article><div className="gear gear-a" /><span>Diferansiyel</span><small>Detaylı bilgi →</small></article><article><div className="gear gear-b" /><span>Şanzıman</span><small>Stokta mevcut</small></article></div></div><div className="contact-float"><MessageCircle size={15} /><span>Hızlı teklif alın</span><b>→</b></div></div>; }

function ProjectCard({ number, title, type, description, href, cta, visual, tone }: { number: string; title: string; type: string; description: string; href: string; cta: string; visual: React.ReactNode; tone: string }) {
  return <motion.article className={`project-card ${tone}`} {...reveal} whileHover={{ y: -8 }}><div className="project-copy"><div className="project-meta"><span>{number}</span><span>{type}</span></div><h3>{title}</h3><p>{description}</p><a href={href} target="_blank" rel="noreferrer">{cta}<ArrowUpRight size={16} /></a></div>{visual}</motion.article>;
}

export default function PortfolioClient() {
  const [menuOpen, setMenuOpen] = useState(false);
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, { stiffness: 130, damping: 28, restDelta: 0.001 });
  return <main>
    <motion.div className="scroll-progress" style={{ scaleX }} />
    <nav className="nav-shell" aria-label="Ana navigasyon"><a href="#top" className="brand-mark" aria-label="sarikayadevs.com ana sayfa"><Braces size={19} /><span>sarıkaya<em>devs</em></span></a><div className="nav-links">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div><a className="nav-status" href="#iletisim"><span />Yeni proje için müsait</a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menüyü aç" aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></nav>
    {menuOpen && <motion.div className="mobile-menu" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }}>{navItems.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}<ArrowDownRight size={18} /></a>)}</motion.div>}

    <section className="hero" id="top"><div className="hero-grid" aria-hidden="true" /><div className="hero-glow" aria-hidden="true" /><div className="hero-scene" aria-hidden="true"><HeroScene /></div><div className="hero-content">
      <motion.div className="eyebrow" initial={{ opacity: 0, x: -18 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.15 }}><CircleDot size={13} /> FULL-STACK / CYBERSECURITY / DIGITAL PRODUCTS</motion.div>
      <motion.p className="hero-kicker" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }}>Merhaba, ben</motion.p><motion.h1 initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.75, delay: 0.2 }}>Muhammed<span>.</span></motion.h1>
      <motion.div className="hero-domain" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}><span>founder @</span> sarikayadevs.com</motion.div><motion.p className="hero-lead" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.52 }}>Web siteleri, otomasyon araçları ve<br className="desktop-break" /> dijital ürünler geliştiriyorum.</motion.p>
      <motion.div className="hero-actions" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.65 }}><a className="button button-primary" href="#projeler">Projeleri Gör<ArrowDownRight size={17} /></a><a className="button button-ghost" href="#iletisim">İletişime Geç</a><a className="icon-button" href="https://github.com/sarikayadEvs" target="_blank" rel="noreferrer" aria-label="GitHub profili"><Github size={20} /></a></motion.div>
    </div><div className="hero-side-label">BUILD / SHIP / IMPROVE — 2026</div><div className="scroll-cue"><span>SCROLL TO EXPLORE</span><i /></div></section>

    <section className="about section" id="hakkimda"><motion.div className="section-heading" {...reveal}><SectionLabel index="01">HAKKIMDA</SectionLabel><h2>Fikri, çalışan bir ürüne<br /><span>dönüştüren teknik ortak.</span></h2></motion.div><div className="about-layout"><motion.div className="about-copy" {...reveal}><p>Muhammed, <strong>sarikayadevs.com</strong> çatısı altında işletmeler için hızlı, güvenilir ve kullanımı kolay web çözümleri geliştirir. Müşteri siteleri, ürün tanıtım sayfaları, yönetilebilir içerik yapıları ve geliştirici araçları üzerine çalışır.</p><div className="about-note"><ShieldCheck size={22} /><span>Güvenlik bakış açısı, temiz kod ve sürdürülebilir geliştirme her projenin temelinde.</span></div></motion.div><motion.div className="skill-cloud" {...reveal}>{skills.map((skill, index) => <span key={skill} className={index === 0 || index === 4 ? "featured" : ""}><Check size={13} />{skill}</span>)}</motion.div></div><div className="signal-strip"><span>01 / DEFINE</span><i /><span>02 / DESIGN</span><i /><span>03 / DEVELOP</span><i /><span>04 / DEPLOY</span></div></section>

    <section className="projects section" id="projeler"><motion.div className="section-heading split" {...reveal}><div><SectionLabel index="02">SEÇİLİ PROJELER</SectionLabel><h2>Gerçek ihtiyaca göre<br /><span>tasarlanmış işler.</span></h2></div><p>Her proje; net bir amaç, sağlam bir altyapı ve son kullanıcı için kolay bir deneyim üzerine kurulur.</p></motion.div><div className="project-list">
      <ProjectCard number="01" title="eHub Steam Game Adder" type="DEVELOPER TOOL / AUTOMATION" description="Steam oyun ekleme ve yönetim sürecini kolaylaştırmaya odaklanan bir yardımcı araç." href="https://github.com/sarikayadEvs?tab=repositories" cta="GitHub’da Gör" visual={<SteamMockup />} tone="cyan" />
      <ProjectCard number="02" title="Çoban Çökerten" type="SPOR KOÇLUĞU WEB SİTESİ" description="Spor koçluğu hizmetlerini tanıtmak, güven oluşturmak ve ziyaretçileri iletişime yönlendirmek için hazırlanmış müşteri sitesi." href="https://cobancokerten.com.tr" cta="Siteyi Gör" visual={<CoachMockup />} tone="lime" />
      <ProjectCard number="03" title="Ahmet Zeybek" type="SANAYİ / KATALOG / İLETİŞİM" description="Oto diferansiyel ve şanzıman parçaları için ürün gösterimi, müşteri yorumları, konum ve hızlı iletişim içeren satış odaklı web sitesi." href="https://ahmetzeybek.com" cta="Siteyi Gör" visual={<IndustryMockup />} tone="amber" />
    </div><motion.a className="github-band" href="https://github.com/sarikayadEvs?tab=repositories" target="_blank" rel="noreferrer" {...reveal}><div><Github size={28} /><span><small>OPEN SOURCE / EXPERIMENTS</small>Diğer GitHub Projeleri</span></div><div className="repo-preview"><i>R</i><span>Yeni araçlar ve deneyler için GitHub profilini keşfet.</span></div><ArrowUpRight size={28} /></motion.a></section>

    <section className="services section" id="hizmetler"><motion.div className="section-heading split" {...reveal}><div><SectionLabel index="03">HİZMETLER</SectionLabel><h2>İş hedeflerine odaklanan<br /><span>dijital çözümler.</span></h2></div><div className="section-counter">06<span>CAPABILITIES</span></div></motion.div><div className="services-grid">{services.map((service, index) => { const Icon = service.icon; return <motion.article key={service.title} {...reveal} transition={{ delay: index * 0.05 }}><span className="service-number">0{index + 1}</span><Icon size={25} /><h3>{service.title}</h3><p>{service.text}</p><ArrowUpRight className="service-arrow" size={18} /></motion.article>; })}</div></section>
    <section className="process section" id="surec"><motion.div className="section-heading" {...reveal}><SectionLabel index="04">SÜREÇ</SectionLabel><h2>Belirsizliği azaltan,<br /><span>şeffaf bir çalışma akışı.</span></h2></motion.div><div className="process-track">{process.map((item, index) => <motion.div key={item} className="process-step" {...reveal} transition={{ delay: index * 0.05 }}><div className="step-node"><span>{String(index + 1).padStart(2, "0")}</span></div><div><small>{index < 2 ? "DISCOVER" : index < 4 ? "BUILD" : "DELIVER"}</small><h3>{item}</h3></div></motion.div>)}</div></section>
    <section className="contact section" id="iletisim"><div className="contact-orbit one" aria-hidden="true" /><div className="contact-orbit two" aria-hidden="true" /><motion.div className="contact-inner" {...reveal}><div className="contact-status"><span />LET’S BUILD SOMETHING USEFUL</div><h2>Bir fikrin varsa<br /><span>birlikte netleştirelim.</span></h2><p>Bir web sitesi, otomasyon aracı veya dijital ürün fikrin varsa; kapsamı, doğru teknolojiyi ve en hızlı yolu birlikte belirleyelim.</p><div className="contact-actions"><a className="contact-button instagram" href="https://www.instagram.com/ily.muh4mm3d/" target="_blank" rel="noreferrer"><Instagram size={19} />Instagram<ArrowUpRight size={17} /></a><a className="contact-button" href="mailto:sarikayadevs0@gmail.com"><Mail size={19} />E-posta<ArrowUpRight size={17} /></a><a className="contact-button" href="https://discord.com/app" target="_blank" rel="noreferrer" aria-label="Discord: peterbenjaminparkerr"><MessageCircle size={19} />Discord<ArrowUpRight size={17} /></a><a className="contact-button" href="https://github.com/sarikayadEvs" target="_blank" rel="noreferrer"><Github size={19} />GitHub<ArrowUpRight size={17} /></a></div><div className="contact-handles"><span>@ily.muh4mm3d</span><span>sarikayadevs0@gmail.com</span><span>discord: peterbenjaminparkerr</span></div></motion.div></section>
    <footer><a href="#top" className="brand-mark"><Braces size={18} /><span>sarıkaya<em>devs</em></span></a><span>© 2026 Muhammed. Built with intent.</span><div><a href="#hakkimda">Hakkımda</a><a href="#projeler">Projeler</a><a href="#iletisim">İletişim</a></div></footer>
  </main>;
}
